### ISSUE TITLE
Query/filter specimen that have value in certain field

### ISSUE THREAD

**Issue by hettling** [naturalis/nbaR#16]
One aspect I wasn't able to do was call a specimen given that it had data within a certain field. E.g If i want to call specimens of a particular species given that "$item$gatheringEvent$siteCoordinates" has a value. 
How would I go about doing that?

**Comment by rvosa** [comment]
This seems like something that you would use the piping functionality from `dplyr` for

**Comment by hettling** [comment]
This is best done in the query already, to not pull all the data and them filter them. The vignettes have several examples on how to query for non-empty values.
